title: Gibish Archives
description: All versions of gibish in one place!

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
